# Generated by Django 3.0.8 on 2020-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('MD', 'Medium'), ('HI', 'High')], max_length=2)),
                ('state', models.CharField(choices=[('RE', 'Resolved'), ('UN', 'Unresolved')], max_length=2)),
            ],
        ),
    ]
